# Google Cloud App Engine configuration file

runtime: python311

entrypoint: uvicorn main:app --host=0.0.0.0 --port=$PORT

instance_class: F2

env_variables:
  ENVIRONMENT: "production"
  TF_FORCE_GPU_ALLOW_GROWTH: "true"
  TF_CPP_MIN_LOG_LEVEL: "2"
  ENABLE_PROMETHEUS: "true"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 3
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  max_concurrent_requests: 50